name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - '*'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello user, I am triggered because of tag push in branch ${{ github.event.base_ref }} "
        shell: bash
        
      - name: Rollback Release
        if: failure() && steps.create_release.outputs.id != ''
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          id: ${{ steps.create_release.id }}
          # Using a tag name
          tag: ${{ steps.autotagger.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets._TOKEN }}
